config/routes.rb
Rails.application.routes.draw do
  resources :visitors
  root to: 'visitors#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/visitor.rb
class Visitor < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :set_visitor, only: [:show, :edit, :update, :destroy]

  # GET /visitors
  # GET /visitors.json
  def index
    @visitors = Visitor.all
    @visitor = Visitor.new

  end

  # GET /visitors/1
  # GET /visitors/1.json
  def show
  end

  # GET /visitors/new
  def new
    @visitor = Visitor.new
  end

  # GET /visitors/1/edit
  def edit
  end

  # POST /visitors
  # POST /visitors.json
  def create
    @visitor = Visitor.new(visitor_params)

    respond_to do |format|
      if @visitor.save
        format.html { redirect_to @visitor, notice: 'Visitor was successfully created.' }
        format.json { render :show, status: :created, location: @visitor }
      else
        format.html { render :new }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visitors/1
  # PATCH/PUT /visitors/1.json
  def update
    respond_to do |format|
      if @visitor.update(visitor_params)
        format.html { redirect_to @visitor, notice: 'Visitor was successfully updated.' }
        format.json { render :show, status: :ok, location: @visitor }
      else
        format.html { render :edit }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitors/1
  # DELETE /visitors/1.json
  def destroy
    @visitor.destroy
    respond_to do |format|
      format.html { redirect_to visitors_url, notice: 'Visitor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visitor
      @visitor = Visitor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visitor_params
      params.require(:visitor).permit(:name, :dob, :specimen_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 4.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role  => "alert"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
.container
	%nav.navbar.navbar-dark.bg-inverse
		-#%ul.nav.navbar-nav.clearfix
			-#%li.nav-item
			-#  %button.navbar-toggler.hidden-sm-up.nav-link{"aria-controls" => "exCollapsingNavbar2", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#exCollapsingNavbar2", "data-toggle" => "collapse", :type => "button"}
			-#    \ &#9776;
		#exCollapsingNavbar2.collapse.navbar-toggleable-xs
			%h2
				= link_to "DYMO Test", root_path, class: 'navbar-brand'
			%ul.nav.navbar-nav= render 'layouts/navigation_links'

app/views/layouts/application.html.haml
!!!
%html
	%head
		%meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
		%title= content_for?(:title) ? yield(:title) : 'Dymo'
		%meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Dymo'}"}
		= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload'
		= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
		= csrf_meta_tags
	%body
		%header
			= render 'layouts/navigation'
		%main{:role => "main"}
			= render 'layouts/messages'
			= yield

app/views/pages/about.html.haml
- content_for :title do
  About
%h3 About the Website
%p
  This web application was created with
  = link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/')
  from the #{link_to('RailsApps project', 'http://railsapps.github.io/')}.

app/views/visitors/_form.html.haml
= form_for @visitor do |f|
	- if @visitor.errors.any?
		#error_explanation
			%h2= "#{pluralize(@visitor.errors.count, "error")} prohibited this visitor from being saved:"
			%ul
				- @visitor.errors.full_messages.each do |msg|
					%li= msg
	.field
		= f.label :specimen_id
		= f.text_field :specimen_id
	.field
		= f.label :name
		= f.text_field :name
	.field
		= f.label :dob
		= f.date_select :dob
	.actions
		= f.submit 'Save'

app/views/visitors/edit.html.haml
%h1 Editing visitor

= render 'form'

= link_to 'Show', @visitor
\|
= link_to 'Back', visitors_path

app/views/visitors/index.html.haml
%h3 Welcome to DYMO Label Framework JavaScript Library
.header
	#sampleDesctiption
		%span
			This test shows how to use new Label Framework JavaScript Library to display a WYSIWYG label preview and print it.
			%br
			Change values to your liking.  Values will be saved to Visitors table when printed
		%p
.top
.container
	.row
		#input_form.col-md-4
			= form_for @visitor do |f|
				- if @visitor.errors.any?
					#error_explanation
						%h2= "#{pluralize(@visitor.errors.count, "error")} prohibited this visitor from being saved:"
						%ul
							- @visitor.errors.full_messages.each do |msg|
								%li= msg

				.field
					= f.label :specimen_id
					= f.text_field :specimen_id, autofocus: 'autofocus'
				.field
					= f.label :name
					= f.text_field :name
				.field
					= f.label :dob
					= f.date_select :dob, start_year: Date.today.year - 100
				.actions
					-#= f.submit 'Save'

				.printControls
					#printersDiv
						%label{:for => "printersSelect"} Printer:
						%select#printersSelect
					%p
					#printDiv
						%button#printButton{class: 'btn btn-primary'} Print and Save
					%p


		.col-md-4
			.content
				#labelImageDiv
					%img#labelImage{:alt => "label preview", :src => ""}/

app/views/visitors/new.html.haml
%h1 New visitor

= render 'form'

= link_to 'Back', visitors_path

app/views/visitors/show.html.haml
%p#notice= notice

%p
	%b Specimen ID:
	= @visitor.specimen_id
%p
	%b Name:
	= @visitor.name
%p
	%b Dob:
	= @visitor.dob

= link_to 'Edit', edit_visitor_path(@visitor)
\|
= link_to 'Back', visitors_path